@echo off
setlocal

:: 1. Resolve paths dynamically
set SCRIPT_DIR=%~dp0
set CERA_ROOT=%SCRIPT_DIR%..
set CERA_LIB_PATH=%CERA_ROOT%\lib
set PATH=%CERA_LIB_PATH%;%PATH%

set COMMAND=%~1
set FILE=%~2

if "%COMMAND%"=="" goto Help
if "%COMMAND%"=="help" goto Help
if "%COMMAND%"=="clear" goto Clear
if "%COMMAND%"=="version" goto Version

:: All remaining commands require a target file
if "%FILE%"=="" (
    echo Error: Command '%COMMAND%' requires a file argument.
    exit /b 1
)

:: Auto-append .cera for build and exec commands if the file doesn't exist
if "%COMMAND%"=="build" (
    if not exist "%FILE%" if exist "%FILE%.cera" set FILE=%FILE%.cera
)
if "%COMMAND%"=="exec" (
    if not exist "%FILE%" if exist "%FILE%.cera" set FILE=%FILE%.cera
)

:: Isolate the filename for pathing the bytecode output
for %%F in ("%FILE%") do set BASENAME=%%~nF
set BYTECODE_FILE=Out\ByteCode\%BASENAME%.cerabc

if "%COMMAND%"=="build" goto Build
if "%COMMAND%"=="run" goto Run
if "%COMMAND%"=="exec" goto Exec

echo Unknown command: %COMMAND%
goto Help

:Version
echo Cera Compiler ^& Virtual Machine __VERSION__
goto :EOF

:Help
echo Cera Compiler ^& Virtual Machine __VERSION__
echo Usage: cera ^<command^> [file] [args...]
echo.
echo Commands:
echo   version   Show the current Cera version
echo   help      Show this help menu
echo   build     Compile a .cera file to bytecode
echo             Format: cera build ^<file.cera^> [compiler_flags]
echo   run       Execute a compiled bytecode file
echo             Format: cera run [vm_flags] ^<file.cerabc^> [program_args]
echo   exec      Compile and execute a .cera file sequentially
echo             Format: cera exec ^<file.cera^>
echo   clear     Clear all generated bytecode and dumps (Out/ directory)
echo.
echo Compiler Flags (cerac):
echo   -v, --verbose   Enable verbose logging
echo   -t, --tokens    Dump lexer tokens
echo   -a, --ast       Dump parser AST
echo   -s, --analyzer  Dump semantic analyzer environment
echo   -e, --emitter   Dump emitted bytecode
echo   -d, --dump      Enable all dump flags
echo.
echo Virtual Machine Flags (ceravm):
echo   -d              Enable detailed VM logging
echo   -f              Dump VM log to file
echo   -s              Disable silent mode (show logs)
goto :EOF

:Clear
echo Clearing Cera output directories...
if exist Out\ rmdir /s /q Out\
echo Done.
goto :EOF

:Build
:: Shift past 'cera' and 'build' to grab compiler flags
set BUILD_ARGS=
shift
shift
:BuildLoop
if "%~1"=="" goto BuildExec
set BUILD_ARGS=%BUILD_ARGS% %1
shift
goto BuildLoop
:BuildExec
"%SCRIPT_DIR%cerac.exe" "%FILE%" %BUILD_ARGS%
goto :EOF

:Run
:: Shift past 'cera run' to pass everything to ceravm
set RUN_ARGS=
shift
:RunLoop
if "%~1"=="" goto RunExec
set "ARG=%~1"

:: If arg is not a flag, not a local file, try extensions and Out\ByteCode\
if not "%ARG:~0,1%"=="-" (
    if not exist "%ARG%" (
        if exist "%ARG%.cerabc" (
            set "ARG=%ARG%.cerabc"
        ) else if exist "Out\ByteCode\%ARG%" (
            set "ARG=Out\ByteCode\%ARG%"
        ) else if exist "Out\ByteCode\%ARG%.cerabc" (
            set "ARG=Out\ByteCode\%ARG%.cerabc"
        )
    )
)

set RUN_ARGS=%RUN_ARGS% "%ARG%"
shift
goto RunLoop

:RunExec
"%SCRIPT_DIR%ceravm.exe" %RUN_ARGS%
goto :EOF

:Exec
:: Build the source file
"%SCRIPT_DIR%cerac.exe" "%FILE%"
:: If compilation succeeded, run the generated bytecode
if not errorlevel 1 (
    if exist "%BYTECODE_FILE%" (
        "%SCRIPT_DIR%ceravm.exe" "%BYTECODE_FILE%"
    ) else (
        echo Error: Bytecode file %BYTECODE_FILE% not found.
    )
)
goto :EOF